package com.example.catchup.User;

import com.vladmihalcea.hibernate.type.array.ListArrayType;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;


@Entity
@Inheritance (strategy = InheritanceType.JOINED)
@Table(name ="users")
@TypeDef(
        name = "list-array",
        typeClass = ListArrayType.class
)
public class User { //Profile photo ?
    //Unique ID for each user generated by the system
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    //other properties
    private String name;
    private String surname;

    @Column(unique = true)
    private String mail;
    private String password;
    private String role;


    @Type(type = "list-array")
    @Column(
            name = "courseList",
            columnDefinition = "bigInt[]"
    )
    private List<Long> courseList;

    @Type(type = "list-array")
    @Column(
            name = "conversations",
            columnDefinition = "bigInt[]"
    )
    private List<Long> conversations;


    //default constructor for JPA
    public User() {

    }

    //constructor for init of the properties of user.
    public User(String name, String surname, String mail,String password,String role){
        this.name = name;
        this.mail = mail;
        this.surname = surname;
        this.password = password;
        this.role = role;
        this.courseList = new ArrayList<>(0);
        this.conversations = new ArrayList<>(0);
    }

    public long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getSurname() {
        return surname;
    }

    public String getPassword() {
        return password;
    }

    public String getRole() {
        return role;
    }
    public List<Long> getCourseList() {
        return courseList;
    }
    public List<Long> getConversations() {
        return conversations;
    }
    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", surname='" + surname + '\'' +
                ", mail='" + mail + '\'' +
                ", password='" + password + '\'' +
                ", role='" + role + '\'' +
                ", courseList=" + courseList +
                ", conversations=" + conversations +
                '}';
    }




}

