package com.example.catchup.Group;
import com.example.catchup.Course.Course;
import com.example.catchup.User.Student;
import com.vladmihalcea.hibernate.type.array.ListArrayType;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.springframework.beans.factory.annotation.Autowired;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;
@Entity
public class Advertisement {
    //Unique ID for each ad generated by the system
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    //other properties
    private String title;
    private String description;
    //foreign keys
    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "studentId", referencedColumnName = "studentId")
    private Student studentOwner;

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "GroupId", referencedColumnName = "id")
    private ProjectGroup groupOwner;

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "courseCode", referencedColumnName = "code")
    private Course course;

    public Advertisement() {
    }

    public Advertisement(String title, String description, Student studentOwner, ProjectGroup groupOwner, Course course) {
        this.title = title;
        this.description = description;
        this.studentOwner = studentOwner;
        this.groupOwner = groupOwner;
        this.course = course;
    }

    public long getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getDescription() {
        return description;
    }

    public Student getStudentOwner() {
        return studentOwner;
    }

    public ProjectGroup getGroupOwner() {
        return groupOwner;
    }

    public Course getCourse() {
        return course;
    }

    @Override
    public String toString() {
        return "Advertisement{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", studentOwner=" + studentOwner +
                ", groupOwner=" + groupOwner +
                ", course=" + course +
                '}';
    }
}
