package com.example.catchup.Assignment;

import com.example.catchup.Course.Course;
import com.vladmihalcea.hibernate.type.array.ListArrayType;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Entity
@TypeDef(
        name = "list-array",
        typeClass = ListArrayType.class
)
public class Assignment {
    //Unique ID for each assignment generated by the system
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    //other properties
    private String deadline;
    private String title;
    private String description;
    private int numberOfUploadedAssign;
    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "courseCode", referencedColumnName = "code")
    private Course course;
    //lists
    @Type(type = "list-array")
    @Column(
            name = "courseDocumentInstr",
            columnDefinition = "bigInt[]"
    )
    private List<Long> courseDocumentInstr;

    @Type(type = "list-array")
    @Column(
            name = "artifacts",
            columnDefinition = "bigInt[]"
    )
    private List<Long> artifacts;

    @Type(type = "list-array")
    @Column(
            name = "requests",
            columnDefinition = "text[]"
    )
    private List<String> requests;

    public Assignment() {
    }

    public Assignment(String deadline, String title, String description, Course course) {
        this.deadline = deadline;
        this.title = title;
        this.description = description;
        this. numberOfUploadedAssign = 0;
        this.courseDocumentInstr = new ArrayList<>(0);
        this.artifacts = new ArrayList<>(0);
        this.requests = new ArrayList<>(0);
        this.course= course;
    }
    public Assignment(String deadline, String title,ArrayList<Long> courseDocuments, String description,Course course) {
        this.deadline = deadline;
        this.title = title;
        this.description = description;
        this. numberOfUploadedAssign = 0;
        this.courseDocumentInstr = courseDocuments;
        this.artifacts = new ArrayList<>(0);
        this.requests = new ArrayList<>(0);
        this.course= course;
    }

    public Course getCourse() {
        return course;
    }

    public long getId() {
        return id;
    }

    public String getDeadline() {
        return deadline;
    }

    public String getTitle() {
        return title;
    }

    public String getDescription() {
        return description;
    }

    public int getNumberOfUploadedAssign() {
        return numberOfUploadedAssign;
    }

    public List<Long> getCourseDocumentInstr() {
        return courseDocumentInstr;
    }

    public List<Long> getArtifacts() {
        return artifacts;
    }

    public List<String> getRequests() {
        return requests;
    }

    @Override
    public String toString() {
        return "Assignment{" +
                "id=" + id +
                ", deadline=" + deadline +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", numberOfUploadedAssign=" + numberOfUploadedAssign +
                ", course=" + course +
                ", courseDocumentInstr=" + courseDocumentInstr +
                ", artifacts=" + artifacts +
                ", requests=" + requests +
                '}';
    }
}
