package com.example.catchup.Course;
import com.vladmihalcea.hibernate.type.array.ListArrayType;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Entity
public class Announcement {
    //Unique ID for each announcement generated by the system
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String title;
    private String description;
    private Date date;

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "courseCode", referencedColumnName = "code")
    private Course course;

    public Announcement() {

    }

    public Announcement(String title, String description, Date date, Course course) {
        this.title = title;
        this.description = description;
        this.date = date;
        this.course = course;
    }

    public Long getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getDescription() {
        return description;
    }

    public Date getDate() {
        return date;
    }

    public Course getCourse() {
        return course;
    }

    @Override
    public String toString() {
        return "Announcement{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", date=" + date +
                ", course=" + course +
                '}';
    }
}
