package com.example.catchup.Course;
import com.vladmihalcea.hibernate.type.array.ListArrayType;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@TypeDef(
        name = "list-array",
        typeClass = ListArrayType.class
)
public class Course {
    //Unique ID for each course generated by the system
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long code;

    //other properties
    private String name;

    @Type(type = "list-array")
    @Column(
            name = "announcements",
            columnDefinition = "bigInt[]"
    )
    private List<Long> announcements;

    @Type(type = "list-array")
    @Column(
            name = "ads",
            columnDefinition = "bigInt[]"
    )
    private List<Long> ads;

    @Type(type = "list-array")
    @Column(
            name = "assignments",
            columnDefinition = "bigInt[]"
    )
    private List<Long> assignments;

    @Type(type = "list-array")
    @Column(
            name = "courseDocuments",
            columnDefinition = "bigInt[]"
    )
    private List<Long> courseDocuments;

    @Type(type = "list-array")
    @Column(
            name = "polls",
            columnDefinition = "bigInt[]"
    )
    private List<Long> polls;

    @Type(type = "list-array")
    @Column(
            name = "groups",
            columnDefinition = "bigInt[]"
    )
    private List<Long> groups;

    public Course() {
    }

    public Course(String name) {
        this.name = name;
        this.announcements = new ArrayList<>(0);
        this.ads = new ArrayList<>(0);
        this.assignments = new ArrayList<>(0);
        this.polls = new ArrayList<>(0);
        this.courseDocuments = new ArrayList<>(0);
        this.groups = new ArrayList<>(0);
    }

    public Long getCode() {
        return code;
    }

    public String getName() {
        return name;
    }

    public List<Long> getAnnouncements() {
        return announcements;
    }

    public List<Long> getAds() {
        return ads;
    }

    public List<Long> getAssignments() {
        return assignments;
    }

    public List<Long> getCourseDocuments() {
        return courseDocuments;
    }

    public List<Long> getPolls() {
        return polls;
    }

    public List<Long> getGroups() {
        return groups;
    }

    @Override
    public String toString() {
        return "ProjectGroup{" +
                "code='" + code + '\'' +
                ", name='" + name + '\'' +
                ", announcements=" + announcements +
                ", ads=" + ads +
                ", assignments=" + assignments +
                ", courseDocuments=" + courseDocuments +
                ", polls=" + polls +
                ", groups=" + groups +
                '}';
    }
}
