package com.example.demo;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Users {

    //Unique ID for each user generated by the system
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;


    //other properties
    private String name;
    private String surname;
    private String mail;
    private String password;
    private String role;


    //default constructor for JPA
    public Users() {

    }

    //constructor for init of the properties of user.
    public Users(String name, String surname, String mail,String password, String role){
        this.name = name;
        this.mail = mail;
        this.surname = surname;
        this.password = password;
        this.role = role;
    }

    public long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getSurname() {
        return surname;
    }

    public String getPassword() {
        return password;
    }

    public String getRole() {
        return role;
    }

    @Override
    public String toString() {
        return "Users{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", surname='" + surname + '\'' +
                ", mail='" + mail + '\'' +
                ", password='" + password + '\'' +
                ", role='" + role + '\'' +
                '}';
    }

}
